// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/benchmark-settings-preview/Current.tsx": () => import("../components/mockups/benchmark-settings-preview/Current.tsx"),
  "./components/mockups/benchmark-settings-preview/Fixed.tsx": () => import("../components/mockups/benchmark-settings-preview/Fixed.tsx")
};
